// Crop data batch 1: Cereals, Pulses, Oilseeds, Some Vegetables (crops 1–50)
const cropsData1 = [
    // ── CEREALS ──
    { id: 1, name: 'Rice', nameHi: 'चावल', season: 'Kharif', soil: 'Clayey, Loamy', irrigation: 'Flood/Sprinkler – 1200-1500mm', fertilizer: 'N:P:K = 120:60:60 kg/ha, urea in 3 splits', pests: 'Brown Planthopper, Stem Borer, Leaf Folder', image: '🌾', color: 'from-green-400 to-emerald-600', bestPractices: ['Maintain 2-5cm standing water in vegetative stage', 'Drain 15 days before harvest'], communityQA: [{ question: 'Why are leaf tips turning yellow?', answer: 'Likely nitrogen deficiency or brown spot. Apply urea or check for fungi.' }], storage: 'Dry to 14% moisture before storage', marketDynamics: 'High domestic and export demand' },
    { id: 2, name: 'Wheat', nameHi: 'गेहूँ', season: 'Rabi', soil: 'Loamy, Well-drained', irrigation: 'Furrow/Drip – 4-6 irrigations', fertilizer: 'N:P:K = 120:60:40 kg/ha, split nitrogen', pests: 'Aphids, Yellow Rust, Loose Smut', image: '🌿', color: 'from-yellow-400 to-amber-600', bestPractices: ['Pre-irrigate before sowing', 'Apply 1st N dose at CRI stage (20-25 days)'], communityQA: [{ question: 'How many irrigations needed?', answer: '4-6 at key stages: CRI, tillering, jointing, flowering, milking, dough.' }], storage: 'Dry to 10-12%, use hermetic bags', marketDynamics: 'Prices peak Nov-Jan pre-harvest' },
    { id: 3, name: 'Maize', nameHi: 'मक्का', season: 'Kharif', soil: 'Sandy Loam, OM-rich', irrigation: 'Furrow/Drip – critical at silking', fertilizer: 'N:P:K = 150:75:50 kg/ha', pests: 'Fall Armyworm, Stem Borer, Aphids', image: '🌽', color: 'from-orange-400 to-yellow-600', bestPractices: ['Weed control for first 30-45 days', 'Avoid waterlogging'], communityQA: [{ question: 'How to control Fall Armyworm?', answer: 'Use pheromone traps; spray biopesticides targeting the whorl.' }], storage: 'Dry to 12%, use elevated bins', marketDynamics: 'Growing demand from poultry and ethanol' },
    { id: 4, name: 'Sorghum', nameHi: 'ज्वार', season: 'Kharif', soil: 'Loamy, Slightly Alkaline', irrigation: 'Rainfed; 400-600mm', fertilizer: 'N:P:K = 80:40:40 kg/ha', pests: 'Shoot Fly, Midge, Aphids', image: '🌾', color: 'from-yellow-500 to-orange-500', bestPractices: ['Sow at onset of monsoon', 'Use improved midge-resistant varieties'], communityQA: [{ question: 'What is shoot fly damage?', answer: 'Dead heart in seedlings. Delay sowing or use thiamethoxam seed treatment.' }], storage: 'Dry to 12%, store in gunny bags', marketDynamics: 'Used as food and fodder; demand stable' },
    { id: 5, name: 'Pearl Millet', nameHi: 'बाजरा', season: 'Kharif', soil: 'Sandy, Light Loamy', irrigation: 'Rainfed; 300-500mm', fertilizer: 'N:P:K = 60:30:30 kg/ha', pests: 'Downy Mildew, Ergot, Stem Borer', image: '🌾', color: 'from-amber-400 to-yellow-600', bestPractices: ['Plant on ridges for drainage', 'Treat seed with Metalaxyl against Downy Mildew'], communityQA: [{ question: 'What causes ear head not to emerge?', answer: 'Could be ergot or downy mildew. Use resistant varieties and rogue infected plants.' }], storage: 'Dry to 10%, well-ventilated storage', marketDynamics: 'Nutritious crop, demand growing in health food segment' },
    { id: 6, name: 'Finger Millet', nameHi: 'रागी', season: 'Kharif', soil: 'Red Loamy, Sandy Loam', irrigation: 'Rainfed; 700-1000mm', fertilizer: 'N:P:K = 60:30:30 kg/ha', pests: 'Blast, Aphids, Ear Caterpillar', image: '🌾', color: 'from-red-300 to-rose-500', bestPractices: ['Transplant 25-day seedlings for better yield', 'Top dress with N at tillering'], communityQA: [{ question: 'What is ragi blast?', answer: 'A fungal disease causing diamond-shaped lesions. Use Tricyclazole spray.' }], storage: 'Dry well; long shelf life up to 10 years', marketDynamics: 'Nutrition superfood; demand rising' },
    { id: 7, name: 'Barley', nameHi: 'जौ', season: 'Rabi', soil: 'Sandy Loam, Well-drained', irrigation: '2-3 irrigations at CRI and booting', fertilizer: 'N:P:K = 60:30:30 kg/ha', pests: 'Loose Smut, Stripe Disease, Aphids', image: '🌾', color: 'from-yellow-300 to-amber-400', bestPractices: ['Sow in November for best yield', 'Avoid late irrigation before harvest'], communityQA: [{ question: 'Which barley variety is best for malt?', answer: 'Malt varieties like Jyoti and K-572 have high starch and low protein.' }], storage: 'Dry to 12%, cool dry warehouse', marketDynamics: 'Malt barley in demand from breweries; feed barley stable' },
    { id: 8, name: 'Oats', nameHi: 'जई', season: 'Rabi', soil: 'Loamy, Slightly Acidic', irrigation: '2-3 irrigations needed', fertilizer: 'N:P:K = 80:40:40 kg/ha', pests: 'Crown Rust, Smut, Aphids', image: '🌾', color: 'from-lime-300 to-green-400', bestPractices: ['Sow in mid-October for forage', 'Cut before flowering for better quality fodder'], communityQA: [{ question: 'Can oats be grown as winter forage?', answer: 'Yes, oats are excellent winter forage. Cut at 50% blooming stage.' }], storage: 'Dry well before storage to prevent mold', marketDynamics: 'Health food market growing; forage demand stable' },
    { id: 9, name: 'Triticale', nameHi: 'ट्रिटिकेल', season: 'Rabi', soil: 'Loamy to Clay Loam', irrigation: '4-5 irrigations', fertilizer: 'N:P:K = 100:50:40 kg/ha', pests: 'Rust, Powdery Mildew', image: '🌾', color: 'from-teal-400 to-cyan-600', bestPractices: ['Good alternative to wheat on marginal soils', 'Resistant to many wheat diseases'], communityQA: [{ question: 'What is triticale used for?', answer: 'Used for bread, fodder, and ethanol production.' }], storage: 'Dry to 12%', marketDynamics: 'Niche market, growing interest as climate-resilient crop' },
    { id: 10, name: 'Buckwheat', nameHi: 'कुट्टू', season: 'Kharif', soil: 'Sandy, Acidic, Poor soils tolerated', irrigation: 'Rainfed; tolerates low rainfall', fertilizer: 'N:P:K = 40:20:20 kg/ha', pests: 'Aphids, Caterpillars', image: '🌿', color: 'from-rose-300 to-pink-500', bestPractices: ['Short crop cycle (70-75 days)', 'Good crop for hill regions and marginal soils'], communityQA: [{ question: 'Is buckwheat gluten-free?', answer: 'Yes, buckwheat is naturally gluten-free and rich in rutin.' }], storage: 'Dry and store cool', marketDynamics: 'High demand as gluten-free health food' },

    // ── PULSES ──
    { id: 11, name: 'Chickpea', nameHi: 'चना', season: 'Rabi', soil: 'Sandy Loam to Clay Loam', irrigation: '1-2 irrigations; rainfed mostly', fertilizer: 'N:P:K = 20:60:40 kg/ha + Rhizobium', pests: 'Pod Borer, Wilt, Blight', image: '🫛', color: 'from-yellow-400 to-amber-500', bestPractices: ['Seed treat with Trichoderma for wilt control', 'Avoid excessive nitrogen; it fixes its own'], communityQA: [{ question: 'How to manage pod borer?', answer: 'Use pheromone traps, spray HaNPV or Chloropyrifos at egg hatching.' }], storage: 'Dry to 9-10% for long storage', marketDynamics: 'High demand; MSP supported crop' },
    { id: 12, name: 'Pigeon Pea', nameHi: 'अरहर/तुअर', season: 'Kharif', soil: 'Loamy to Sandy Loam', irrigation: 'Rainfed; 600-650mm', fertilizer: 'N:P:K = 20:50:30 kg/ha', pests: 'Pod Borer, Wilt, Sterility Mosaic', image: '🫛', color: 'from-orange-300 to-amber-500', bestPractices: ['Intercrop with sorghum or maize', 'Apply 2% DAP foliar spray at flowering'], communityQA: [{ question: 'Why do plants yellow and die suddenly?', answer: 'Fusarium wilt. Use resistant varieties and seed treat with Carbendazim.' }], storage: 'Dry to 10%; store in airtight containers', marketDynamics: 'Very high demand; chronic domestic shortage' },
    { id: 13, name: 'Lentil', nameHi: 'मसूर', season: 'Rabi', soil: 'Loamy, Sandy Loam', irrigation: '1-2 irrigations; mostly rainfed', fertilizer: 'N:P:K = 20:50:25 kg/ha', pests: 'Aphids, Rust, Wilt', image: '🫘', color: 'from-red-300 to-rose-400', bestPractices: ['Sow in well-prepared seed bed', 'Avoid water stagnation'], communityQA: [{ question: 'What causes rust in lentils?', answer: 'Uromyces viciae-fabae fungus. Spray Mancozeb or Propiconazole.' }], storage: 'Store dry in cool conditions', marketDynamics: 'High demand; often in price deficit domestically' },
    { id: 14, name: 'Mung Bean', nameHi: 'मूँग', season: 'Kharif/Zaid', soil: 'Sandy Loam, Well-drained', irrigation: '4-5 irrigations if not rainfed', fertilizer: 'N:P:K = 20:50:30 kg/ha', pests: 'Yellow Mosaic Virus, Pod Borer', image: '🫘', color: 'from-green-400 to-lime-500', bestPractices: ['Short duration (60-65 days), good catch crop', 'Whitefly control critical for YMV prevention'], communityQA: [{ question: 'How to control Yellow Mosaic?', answer: 'No cure; remove infected plants early. Control whitefly vector with Imidacloprid.' }], storage: 'Dry to 9%, store in airtight bags', marketDynamics: 'High demand for dal and sprouts' },
    { id: 15, name: 'Black Gram', nameHi: 'उड़द', season: 'Kharif/Rabi', soil: 'Loamy, Well-drained', irrigation: 'Rainfed or 3-4 irrigations', fertilizer: 'N:P:K = 20:50:30 kg/ha', pests: 'Yellow Mosaic, Leaf Crinkle, Pod Borer', image: '🫘', color: 'from-gray-500 to-slate-700', bestPractices: ['Use YMV-resistant varieties', 'Avoid sowing in virus-endemic areas without IPM'], communityQA: [{ question: 'Leaves are curling and distorted?', answer: 'Likely Leaf Crinkle Virus. Remove infected plants; control aphid vectors.' }], storage: 'Dry to 9%', marketDynamics: 'Key ingredient for urad dal and idli batter; steady demand' },
    { id: 16, name: 'Kidney Bean', nameHi: 'राजमा', season: 'Kharif/Rabi', soil: 'Well-drained Loam', irrigation: '5-6 irrigations', fertilizer: 'N:P:K = 30:60:30 kg/ha', pests: 'Pod Borer, Rust, Angular Leaf Spot', image: '🫘', color: 'from-red-500 to-rose-700', bestPractices: ['Stake climbing varieties', 'Avoid overhead irrigation to reduce rust'], communityQA: [{ question: 'When to harvest?', answer: 'Harvest when 75-80% pods are yellow-brown (for dry beans).' }], storage: 'Dry to 10-12%', marketDynamics: 'Popular in north India; premium prices' },
    { id: 17, name: 'Cowpea', nameHi: 'लोबिया', season: 'Kharif/Summer', soil: 'Sandy Loam, Tolerates Poor Soils', irrigation: 'Rainfed or 3-4 irrigations', fertilizer: 'N:P:K = 20:50:30 kg/ha', pests: 'Aphids, Thrips, Pod Borer', image: '🫛', color: 'from-green-300 to-teal-500', bestPractices: ['Dual purpose as food and fodder', 'Fixes nitrogen; good for soil health'], communityQA: [{ question: 'Can cowpea tolerate drought?', answer: 'Yes, it is one of the most drought-tolerant legumes.' }], storage: 'Dry to 10%', marketDynamics: 'Increasing demand as climate-resilient crop' },
    { id: 18, name: 'Horse Gram', nameHi: 'कुलथी', season: 'Kharif', soil: 'Sandy Loam, Marginal Soils', irrigation: 'Rainfed; very drought tolerant', fertilizer: 'N:P:K = 15:40:20 kg/ha', pests: 'Aphids, Leaf Spot', image: '🫘', color: 'from-amber-600 to-orange-700', bestPractices: ['Good for dry-land farming', 'Sow on conserved moisture before rains cease'], communityQA: [{ question: 'What is horse gram good for?', answer: 'Rich in protein; used in rasam, soup; beneficial in weight loss diets.' }], storage: 'Dry well; long shelf life', marketDynamics: 'Niche market; health food demand rising' },
    { id: 19, name: 'Field Peas', nameHi: 'मटर', season: 'Rabi', soil: 'Loamy, Well-drained', irrigation: '2-3 irrigations', fertilizer: 'N:P:K = 25:60:30 kg/ha', pests: 'Powdery Mildew, Aphids, Pod Borer', image: '🫛', color: 'from-green-400 to-emerald-500', bestPractices: ['Sow in October-November for best yield', 'Inoculate with Rhizobium'], communityQA: [{ question: 'How to manage Powdery Mildew?', answer: 'Spray Sulphur or Carbendazim at first sign.' }], storage: 'For dry peas: dry to 10%; fresh peas refrigerate', marketDynamics: 'High demand both fresh and dry' },
    { id: 20, name: 'Faba Bean', nameHi: 'बाकला', season: 'Rabi', soil: 'Heavy Clay, Loamy', irrigation: '2-3 irrigations', fertilizer: 'N:P:K = 20:60:40 kg/ha', pests: 'Aphids, Chocolate Spot, Bean Weevil', image: '🫘', color: 'from-purple-300 to-violet-500', bestPractices: ['Sow early for best yield', 'Important rotation crop; improves soil N'], communityQA: [{ question: 'What are the symptoms of Chocolate Spot?', answer: 'Brown spots on leaves in humid conditions. Spray with Benomyl or Iprodione.' }], storage: 'Dry to 12%', marketDynamics: 'Niche crop; good export potential' },

    // ── OILSEEDS ──
    { id: 21, name: 'Groundnut', nameHi: 'मूँगफली', season: 'Kharif', soil: 'Sandy Loam, Well-drained', irrigation: '3-4 irrigations; critical at pegging', fertilizer: 'N:P:K = 25:50:50 kg/ha + Gypsum', pests: 'Tikka Leaf Spot, Bud Necrosis, Aphids', image: '🥜', color: 'from-yellow-500 to-orange-600', bestPractices: ['Apply gypsum at pegging stage', 'Avoid waterlogging; pods rot'], communityQA: [{ question: 'Why are pods not developing?', answer: 'Could be calcium/gypsum deficiency. Apply gypsum 200 kg/ha at pegging.' }], storage: 'Dry to 8-9% to prevent aflatoxin', marketDynamics: 'Key oilseed; also edible as snack; steady demand' },
    { id: 22, name: 'Sunflower', nameHi: 'सूरजमुखी', season: 'Rabi/Kharif', soil: 'Loamy, Well-drained', irrigation: '6-8 irrigations', fertilizer: 'N:P:K = 90:60:60 kg/ha', pests: 'Head Borer, Aphids, Alternaria Blight', image: '🌻', color: 'from-yellow-400 to-amber-500', bestPractices: ['Hand pollinate heads early morning for better seed set', 'Harvest when back of head turns yellow-brown'], communityQA: [{ question: 'How to ensure good pollination?', answer: 'Ensure bee colonies are nearby; do hand pollination if needed.' }], storage: 'Dry to 8-9%', marketDynamics: 'Good oil content; demand from edible oil industry' },
    { id: 23, name: 'Mustard', nameHi: 'सरसों', season: 'Rabi', soil: 'Loamy, Sandy Loam', irrigation: '1-2 irrigations', fertilizer: 'N:P:K = 80:40:40 kg/ha + Sulphur', pests: 'Aphids, Alternaria Blight, White Rust', image: '🌼', color: 'from-yellow-400 to-amber-400', bestPractices: ['Sow in last week of October', 'Apply Sulphur for quality improvement'], communityQA: [{ question: 'How to manage aphids in mustard?', answer: 'Spray Dimethoate or Imidacloprid; leave natural enemies like ladybird beetles.' }], storage: 'Dry to 7-8%', marketDynamics: 'Major Rabi oilseed; high domestic demand' },
    { id: 24, name: 'Sesame', nameHi: 'तिल', season: 'Kharif', soil: 'Sandy Loam, Well-drained', irrigation: '3-4 irrigations', fertilizer: 'N:P:K = 40:20:20 kg/ha', pests: 'Leaf Webber, Phyllody, Gall Midge', image: '🌿', color: 'from-amber-300 to-yellow-400', bestPractices: ['Row crop on well-prepared seedbed', 'Harvest before capsules split open'], communityQA: [{ question: 'When to harvest?', answer: 'When 75% of capsules turn yellow-brown; early morning harvesting prevents seed shedding.' }], storage: 'Dry to 6-7%', marketDynamics: 'Premium price; export demand strong' },
    { id: 25, name: 'Linseed/Flaxseed', nameHi: 'अलसी', season: 'Rabi', soil: 'Loamy, Clay Loam', irrigation: '2-3 irrigations', fertilizer: 'N:P:K = 40:30:30 kg/ha', pests: 'Rust, Powdery Mildew, Bud Fly', image: '🌸', color: 'from-blue-400 to-indigo-500', bestPractices: ['Use late-maturing varieties for higher oil content', 'Harvest when 75% bolls brown'], communityQA: [{ question: 'What is flaxseed used for?', answer: 'Oil for industrial use; seeds rich in Omega-3 for health food market.' }], storage: 'Dry to 8-9%', marketDynamics: 'Growing demand in health food and nutraceutical sector' },
    { id: 26, name: 'Safflower', nameHi: 'कुसुम', season: 'Rabi', soil: 'Deep Black, Clay Loam', irrigation: '1-2 irrigations; drought tolerant', fertilizer: 'N:P:K = 40:30:30 kg/ha', pests: 'Aphids, Caterpillar, Fly', image: '🌸', color: 'from-orange-400 to-red-500', bestPractices: ['Sow in November on deep soils', 'Crop thrives on stored soil moisture'], communityQA: [{ question: 'Can safflower be grown on rain-fed conditions?', answer: 'Yes, it is highly drought-tolerant and suitable for dry land farming.' }], storage: 'Dry well before storage', marketDynamics: 'Niche oilseed; also used for natural dye' },
    { id: 27, name: 'Castor', nameHi: 'अरंडी', season: 'Kharif', soil: 'Sandy Loam, Red Soil', irrigation: '3-4 irrigations', fertilizer: 'N:P:K = 60:30:30 kg/ha', pests: 'Semilooper, Capsule Borer, Red Spider Mite', image: '🌿', color: 'from-green-600 to-teal-700', bestPractices: ['Harvest multiple times as spikes mature', 'Plant on ridges for good drainage'], communityQA: [{ question: 'What is castor oil used for?', answer: 'Industrial lubricant, biodiesel, cosmetics, and pharmaceuticals.' }], storage: 'Dry seeds to 8%', marketDynamics: 'Strong industrial demand; good export potential' },
    { id: 28, name: 'Rapeseed', nameHi: 'तोरिया', season: 'Rabi', soil: 'Loamy, Sandy Loam', irrigation: '1-2 irrigations', fertilizer: 'N:P:K = 60:30:30 kg/ha', pests: 'Aphids, White Rust, Sclerotinia', image: '🌼', color: 'from-yellow-300 to-yellow-500', bestPractices: ['Short-duration crop (80-90 days)', 'Earlier sowing than mustard'], communityQA: [{ question: 'Difference between toria and mustard?', answer: 'Toria is faster-maturing; smaller seeds; lower oil content than mustard.' }], storage: 'Dry to 7%', marketDynamics: 'Companion oilseed to mustard; local demand stable' },
    { id: 29, name: 'Niger Seed', nameHi: 'रामतिल', season: 'Kharif', soil: 'Red Sandy Loam, Marginal Soils', irrigation: 'Rainfed', fertilizer: 'N:P:K = 30:30:15 kg/ha', pests: 'Gall Fly, Leaf Blight', image: '🌸', color: 'from-purple-400 to-violet-600', bestPractices: ['Grows well on marginal soils', 'Good rotation crop'], communityQA: [{ question: 'What is niger seed used for?', answer: 'Oil for cooking; seeds for bird feed; also used in tribals areas of central India.' }], storage: 'Dry to 8%', marketDynamics: 'Niche; tribal and bird-feed market' },
    { id: 30, name: 'Soybean', nameHi: 'सोयाबीन', season: 'Kharif', soil: 'Well-drained Clay Loam', irrigation: 'Furrow – 450-700mm', fertilizer: 'N:P:K = 30:60:40 kg/ha (self-fixes N)', pests: 'Girdle Beetle, Leaf Caterpillar, Rust', image: '🫘', color: 'from-lime-400 to-green-600', bestPractices: ['Inoculate with Rhizobium before sowing', 'Sow on broad bed furrows (BBF)'], communityQA: [{ question: 'When to watch for girdle beetle?', answer: 'Monitor 25-30 days after sowing; look for 2 parallel rings on stems.' }], storage: 'Dry to 10%', marketDynamics: 'Driven by edible oil and poultry meal demand' },

    // ── VEGETABLES ──
    { id: 31, name: 'Tomato', nameHi: 'टमाटर', season: 'Rabi/Kharif', soil: 'Sandy Loam, OM-rich', irrigation: 'Drip – 600-800mm', fertilizer: 'N:P:K = 120:60:80 kg/ha', pests: 'Fruit Borer, Whitefly, Early Blight', image: '🍅', color: 'from-red-400 to-rose-600', bestPractices: ['Stake plants for better quality', 'Consistent watering prevents Blossom End Rot'], communityQA: [{ question: 'What is Blossom End Rot?', answer: 'Dark patch on fruit bottom due to Ca deficiency from irregular watering.' }], storage: 'Store 10-15°C for shelf life', marketDynamics: 'High daily price fluctuations at mandi' },
    { id: 32, name: 'Onion', nameHi: 'प्याज', season: 'Rabi', soil: 'Loamy/Clay Loam', irrigation: 'Drip/Sprinkler – 350-550mm', fertilizer: 'N:P:K = 100:50:50 kg/ha', pests: 'Thrips, Purple Blotch, Damping Off', image: '🧅', color: 'from-purple-400 to-violet-600', bestPractices: ['Stop irrigation 15 days before harvest', 'Cure in shade 10-15 days before storage'], communityQA: [{ question: 'How to prevent neck rot in storage?', answer: 'Ensure tops fully dry; store in ventilated structures.' }], storage: 'Ventilated Kanda Chawl storage', marketDynamics: 'Cyclical price spikes; high political sensitivity' },
    { id: 33, name: 'Potato', nameHi: 'आलू', season: 'Rabi', soil: 'Sandy Loam, Loose', irrigation: 'Sprinkler/Furrow – 5-6 irrigations', fertilizer: 'N:P:K = 120:80:100 kg/ha', pests: 'Late Blight, Aphids, Cut Worm', image: '🥔', color: 'from-amber-400 to-yellow-600', bestPractices: ['Plant certified disease-free seed tubers', 'Earth up after 45 days to prevent greening'], communityQA: [{ question: 'How to spot Late Blight?', answer: 'Water-soaked patches on leaves turning brown. Spray Mancozeb or Metalaxyl.' }], storage: 'Cold storage at 2-4°C', marketDynamics: 'Price very sensitive to cold storage stock levels' },
    { id: 34, name: 'Brinjal', nameHi: 'बैंगन', season: 'Year-round', soil: 'Sandy Loam to Clay Loam', irrigation: 'Drip – 500-700mm', fertilizer: 'N:P:K = 100:50:50 kg/ha', pests: 'Shoot and Fruit Borer, Jassids, Mites', image: '🍆', color: 'from-violet-500 to-purple-700', bestPractices: ['Stake tall varieties', 'Remove borer-infected shoots and fruits immediately'], communityQA: [{ question: 'How to manage Shoot & Fruit Borer?', answer: 'Use pheromone traps; spray with Spinosad or Chlorantraniliprole.' }], storage: 'Store at 10-12°C, high humidity', marketDynamics: 'Stable demand year-round' },
    { id: 35, name: 'Okra', nameHi: 'भिंडी', season: 'Kharif/Summer', soil: 'Sandy Loam, Well-drained', irrigation: 'Drip – 400-500mm', fertilizer: 'N:P:K = 80:40:40 kg/ha', pests: 'Yellow Vein Mosaic Virus, Jassids, Aphids', image: '🫛', color: 'from-green-500 to-lime-600', bestPractices: ['Harvest tender pods every 2 days', 'Control whitefly to manage YVMV'], communityQA: [{ question: 'What is YVMV?', answer: 'Yellow Vein Mosaic Virus spread by whitefly. Use resistant varieties; spray Imidacloprid.' }], storage: 'Keep pods at 10-15°C', marketDynamics: 'Consistent market demand; export potential for frozen okra' },
    { id: 36, name: 'Cauliflower', nameHi: 'फूलगोभी', season: 'Rabi/October-March', soil: 'Sandy Loam, Fertile', irrigation: 'Sprinkler – 5-6 irrigations', fertilizer: 'N:P:K = 120:60:60 kg/ha', pests: 'Diamond Back Moth, Aphids, Club Root', image: '🥦', color: 'from-white to-gray-200', bestPractices: ['Blanch curds by covering with inner leaves', 'Apply Boron to prevent hollow stem'], communityQA: [{ question: 'Why are curds turning yellow?', answer: 'Exposure to sunlight. Cover curds with leaves (blanching) to keep white.' }], storage: 'Refrigerate; short shelf life', marketDynamics: 'Seasonal crop; price peaks in summer gap' },
    { id: 37, name: 'Cabbage', nameHi: 'पत्तागोभी', season: 'Rabi', soil: 'Loamy, Fertile', irrigation: 'Sprinkler – 350-560mm', fertilizer: 'N:P:K = 120:60:60 kg/ha', pests: 'Diamond Back Moth, Cabbage Looper, Aphids', image: '🥬', color: 'from-green-300 to-emerald-500', bestPractices: ['Transplant 30-day seedlings', 'Apply Split nitrogen for uniform growth'], communityQA: [{ question: 'How to control Diamond Back Moth?', answer: 'Spray Bt (Bacillus thuringiensis) or Spinosad. Rotate chemicals to avoid resistance.' }], storage: 'Refrigerate at 0-2°C', marketDynamics: 'Steady demand; price dips in peak Rabi season' },
    { id: 38, name: 'Carrot', nameHi: 'गाजर', season: 'Rabi', soil: 'Sandy Loam, Deep, Loose', irrigation: 'Sprinkler – 4-5 irrigations', fertilizer: 'N:P:K = 80:60:60 kg/ha', pests: 'Aphids, Carrot Fly, Alternaria Blight', image: '🥕', color: 'from-orange-400 to-red-400', bestPractices: ['Deep tilling ensures straight, uniform roots', 'Thin seedlings to 5-7cm spacing'], communityQA: [{ question: 'Why are my carrots forked?', answer: 'Stony or compacted soil. Deeply till and remove obstacles before planting.' }], storage: 'Refrigerate or store in cool sand pits', marketDynamics: 'Steady demand; juice segment growing' },
    { id: 39, name: 'Chilli', nameHi: 'मिर्च', season: 'Kharif/Rabi', soil: 'Sandy Loam, OM-rich', irrigation: 'Drip – 700-900mm', fertilizer: 'N:P:K = 100:80:60 kg/ha', pests: 'Thrips, Mites, Chilli Mosaic Virus', image: '🌶️', color: 'from-red-500 to-rose-700', bestPractices: ['Mulch to conserve moisture and control weeds', 'Use sticky traps for thrips monitoring'], communityQA: [{ question: 'Why are fruits distorted and small?', answer: 'Likely Chilli Mosaic Virus from thrips/aphids. Remove infected plants; control vectors.' }], storage: 'Dry red chilli to 8-10% for long storage', marketDynamics: 'High demand; Guntur chilli world-famous for export' },
    { id: 40, name: 'Capsicum', nameHi: 'शिमला मिर्च', season: 'Rabi/Protected Cultivation', soil: 'Sandy Loam, Fertile', irrigation: 'Drip – 400-600mm', fertilizer: 'N:P:K = 100:60:80 kg/ha', pests: 'Mites, Aphids, Powdery Mildew', image: '🫑', color: 'from-green-300 to-yellow-400', bestPractices: ['Grow under net-house or polytunnel for quality', 'Maintain humidity 60-70% for good pollen set'], communityQA: [{ question: 'Which colour capsicums fetch the best price?', answer: 'Red and yellow coloured capsicums fetch premium prices over green ones.' }], storage: 'Refrigerate at 7-10°C', marketDynamics: 'Growing urban demand; hotel & restaurant sector' },
    { id: 41, name: 'Spinach', nameHi: 'पालक', season: 'Rabi', soil: 'Sandy Loam, Rich in OM', irrigation: 'Sprinkler – 3-4 irrigations', fertilizer: 'N:P:K = 80:40:40 kg/ha, high N for leaf', pests: 'Downy Mildew, Leaf Miner, Aphids', image: '🥬', color: 'from-green-600 to-emerald-800', bestPractices: ['Successive sowing every 15 days for regular supply', 'Cut at 5-6 inch height, allowing regrowth'], communityQA: [{ question: 'Can I cut spinach multiple times?', answer: 'Yes, cut-and-come-again works for 3-4 harvests from one sowing.' }], storage: 'Refrigerate; wilts quickly', marketDynamics: 'Year-round demand from urban consumers' },
    { id: 42, name: 'Garlic', nameHi: 'लहसुन', season: 'Rabi', soil: 'Loamy, Sandy Loam', irrigation: 'Furrow/Drip – 7-8 irrigations', fertilizer: 'N:P:K = 100:50:50 kg/ha', pests: 'Thrips, Purple Blotch, White Rot', image: '🧄', color: 'from-gray-200 to-white', bestPractices: ['Plant healthy, large cloves for best yield', 'Harvest when 50% leaves yellow-brown'], communityQA: [{ question: 'How to cure garlic for storage?', answer: 'Dry in shade for 2-3 weeks; tie in bundles or braid for storage.' }], storage: 'Cool dry ventilated store; can store 6+ months', marketDynamics: 'High price premium; domestic and export demand strong' },
    { id: 43, name: 'Ginger', nameHi: 'अदरक', season: 'Kharif', soil: 'Sandy Loam, Laterite, OM-rich', irrigation: 'Furrow/Drip – 1300-1500mm', fertilizer: 'N:P:K = 75:50:50 kg/ha', pests: 'Soft Rot, Shoot Borer, Rhizome Fly', image: '🫚', color: 'from-amber-400 to-yellow-500', bestPractices: ['Mulch with leaves or straw to retain moisture', 'Treat seed rhizomes with Mancozeb before planting'], communityQA: [{ question: 'What is soft rot in ginger?', answer: 'Bacterial disease causing rotting of rhizomes. Drench soil with Bordeaux mixture.' }], storage: 'Store in cool, slightly moist sand pits', marketDynamics: 'High demand; used in food processing and medicine' },
    { id: 44, name: 'Bitter Gourd', nameHi: 'करेला', season: 'Kharif/Summer', soil: 'Sandy Loam, Well-drained', irrigation: 'Drip – 400-500mm', fertilizer: 'N:P:K = 80:40:40 kg/ha', pests: 'Fruit Fly, Aphids, Powdery Mildew', image: '🥒', color: 'from-green-500 to-teal-600', bestPractices: ['Use trellis netting for vertical growth', 'Monitor bait traps for fruit fly'], communityQA: [{ question: 'How to prevent fruit fly damage?', answer: 'Use protein hydrolysate bait traps; cover young fruits with paper bags.' }], storage: 'Refrigerate; shelf life 7-10 days', marketDynamics: 'Health trend driving demand; medicinal value appreciated' },
    { id: 45, name: 'Bottle Gourd', nameHi: 'लौकी', season: 'Kharif/Summer', soil: 'Sandy Loam, Loamy', irrigation: 'Furrow/Drip – 400-500mm', fertilizer: 'N:P:K = 60:40:40 kg/ha', pests: 'Pumpkin Beetle, Aphids, Mosaic Virus', image: '🫙', color: 'from-green-400 to-lime-500', bestPractices: ['Grow on trellis for long straight fruits', 'Harvest tender at 8-10 days after setting'], communityQA: [{ question: 'Why does the fruit become bitter?', answer: 'Wait and harvest at right maturity; over-mature fruits can be bitter.' }], storage: 'Store cool; short shelf life (7-10d)', marketDynamics: 'Daily demand at vegetable markets' },
    { id: 46, name: 'Cucumber', nameHi: 'खीरा', season: 'Kharif/Summer/Rabi', soil: 'Sandy Loam, Well-drained', irrigation: 'Drip – 300-400mm', fertilizer: 'N:P:K = 70:40:40 kg/ha', pests: 'Downy Mildew, Aphids, Fruit Fly', image: '🥒', color: 'from-green-400 to-green-600', bestPractices: ['Harvest every 2 days to encourage further fruiting', 'Use drip to keep foliage dry and reduce mildew'], communityQA: [{ question: 'Why are cucumbers bitter?', answer: 'Water stress or temperature fluctuations cause bitterness. Ensure consistent watering.' }], storage: 'Store 10-13°C, high humidity', marketDynamics: 'Year-round demand; salad and spa markets growing' },
    { id: 47, name: 'Pumpkin', nameHi: 'कद्दू', season: 'Kharif/Summer', soil: 'Sandy Loam, Fertile', irrigation: 'Furrow – 500-600mm', fertilizer: 'N:P:K = 80:40:40 kg/ha', pests: 'Pumpkin Beetle, Red Spider Mite, Aphids', image: '🎃', color: 'from-orange-400 to-amber-600', bestPractices: ['Allow fruit to fully ripen on vine for storage ability', 'Hand pollinate early morning for better fruit set'], communityQA: [{ question: 'How long can pumpkin be stored?', answer: 'Fully mature pumpkins can be stored 3-6 months in cool dry conditions.' }], storage: 'Store at room temp in cool dry store', marketDynamics: 'Long shelf life makes storage and transport easy' },
    { id: 48, name: 'Sweet Potato', nameHi: 'शकरकंद', season: 'Kharif/Rabi', soil: 'Sandy Loam, Well-drained', irrigation: 'Furrow – 4-5 irrigations', fertilizer: 'N:P:K = 75:50:100 kg/ha (K-heavy)', pests: 'Sweet Potato Weevil, Leaf Roller', image: '🍠', color: 'from-orange-500 to-pink-600', bestPractices: ['Plant vine cuttings on raised ridges', 'High potassium encourages root development'], communityQA: [{ question: 'When to harvest?', answer: 'Harvest 3.5-4 months after planting when leaves start yellowing.' }], storage: 'Cure at 29-32°C for one week, then store cool', marketDynamics: 'Growing demand as health-food alternative to potato' },
    { id: 49, name: 'Radish', nameHi: 'मूली', season: 'Rabi/Year-round', soil: 'Sandy Loam, Deep, Loose', irrigation: 'Sprinkler – 3-4 irrigations', fertilizer: 'N:P:K = 80:60:60 kg/ha', pests: 'Aphids, White Rust, Alternaria Blight', image: '🔴', color: 'from-red-300 to-rose-400', bestPractices: ['Quick crop ready in 25-30 days', 'Thin to 5cm spacing for uniform roots'], communityQA: [{ question: 'Radish roots are forked or hairy?', answer: 'Compacted or stony soil. Deep till and add organic matter.' }], storage: 'Refrigerate; use quickly; short shelf life', marketDynamics: 'Cheap and fast crop; regular market demand' },
    { id: 50, name: 'Beetroot', nameHi: 'चुकंदर', season: 'Rabi', soil: 'Sandy Loam, Neutral pH', irrigation: 'Sprinkler – 4-5 irrigations', fertilizer: 'N:P:K = 80:60:50 kg/ha', pests: 'Cercospora Leaf Spot, Aphids', image: '🟣', color: 'from-red-700 to-purple-800', bestPractices: ['Thin seedlings to 8-10cm gap', 'Harvest at 5-7cm diameter for best quality'], communityQA: [{ question: 'Can I eat beetroot leaves?', answer: 'Yes! Beetroot greens are nutritious and can be cooked like spinach.' }], storage: 'Refrigerate trimmed roots; 2-3 week shelf life', marketDynamics: 'Demand growing as health drink and salad ingredient' },
];

module.exports = cropsData1;
